docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query restauranteslateral --number 10 --source facebook --algorithm sentiment140 --lang es --id 41 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@rest_lateral" --number 50 --source twitter --algorithm sentiment140 --lang es --id 42 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query 100MontaditosSpain --number 10 --source facebook --algorithm sentiment140 --lang es --id 43 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@100montaditos" --number 50 --source twitter --algorithm sentiment140 --lang es --id 44 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "restaurantes lateral" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 45 --doc-type lateral
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "100 montaditos" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 46 --doc-type montaditos
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "Cervecería La Sureña" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 47 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "Lizarran" --number 50 --source tripadvisor --algorithm sentiment140 --lang es --id 48 --doc-type lizarran
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "cerveceria.la.surena" --number 10 --source facebook --algorithm sentiment140 --lang es --id 49 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@La__Surena" --number 50 --source twitter --algorithm sentiment140 --lang es --id 50 --doc-type surena
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "LizarranBar" --number 10 --source facebook --algorithm sentiment140 --lang es --id 51 --doc-type lizarran
docker-compose exec orchestrator python -m luigi --module somedi-usecase.workflow StoreTask --query "@lizarranbar" --number 50 --source twitter --algorithm sentiment140 --lang es --id 52 --doc-type lizarran
